# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48003fae0eaf404fbb219d0e401671885486024178ae7334416d53cbad04c0caf99590f4676938bc1fb088ab36b69ae9e63e10916c882d44b292e22252f4b505

test:
  secret_key_base: 4963f27ebb527275a8c3dcf6cf8f0b6182e6a88a1f46418516e6ab7f8836748e847f985c30e77ce8e6fc9880ddedea3980452246d38e692e32b2fcffa9699a8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
